# azure-pipelines-deploy.yaml
trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'kubeconfig.yaml' # Name of your uploaded kubeConfig file

- script: |
    echo "Current working directory:"
    pwd
    echo "Listing files in the working directory:"
    ls -R
  displayName: 'List files'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-k8s-connection-kubeconfig' # Use your actual service connection name
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      $(System.DefaultWorkingDirectory)/k8s/deployment.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-k8s-connection-kubeconfig' # Use your actual service connection name
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      $(System.DefaultWorkingDirectory)/k8s/service.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-k8s-connection-kubeconfig' # Use your actual service connection name
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      $(System.DefaultWorkingDirectory)/k8s/ingress.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-k8s-connection-kubeconfig' # Use your actual service connection name
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      $(System.DefaultWorkingDirectory)/k8s/hpa.yaml
