# azure-pipelines.yml
trigger:
- main
resources:
  pipelines:
  - pipeline: azureBuild
    source: azure-pipelines-build
  - pipeline: azureDeploy
    source: azure-pipelines-deploy
stages:
- stage: Build
  displayName: Run Build Pipeline
  jobs:
  - job: TriggerBuildPipeline
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: kubeconfig.yaml
    - script: echo "Build pipeline finished successfully."
- stage: Deploy
  displayName: Run Deploy Pipeline
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - job: TriggerDeployPipeline
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Deploy pipeline started after build finished successfully."
